version: '3'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/sports_platform.db:/app/sports_platform.db
    restart: always
    environment:
      - DATABASE_URL=sqlite:///sports_platform.db
      - SECRET_KEY=your_production_secret_key
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always